- name: Install sudo
  apt:
    update_cache: yes
    name:
      - sudo
    state: latest

- name: Create 'debian' user 
  ansible.builtin.user:
    name: debian
    groups: sudo
    append: true
    create_home: true
    shell: /bin/bash
    password: "{{ debian_password | password_hash }}"
    state: present