- name: Install qemu-guest-agent
  hosts: vms
  roles:
    - qemu-agent

- name: Include a play for updating all machines
  ansible.builtin.import_playbook: update-machines.yml

- name: Setup monitoring git
  hosts: monitoring
  roles:
    - monitoring

- name: Setup admin-agents git
  hosts: docker
  roles:
    - admin-agents

- name: Setup wireguard machine
  hosts: wireguard
  roles:
    - wireguard

- name: Setup tvheadend machine
  hosts: tvheadend
  roles:
    - tvheadend

- name: Setup homeautomation git
  hosts: homeautomation
  roles:
    - home-automation
