- name: Install qemu-guest-agent
  hosts: vms
  roles:
    - qemu-agent

- name: Include a play for updating all machines
  ansible.builtin.import_playbook: update-machines.yml

- name: Setup monitoring git
  hosts: monitoring
  roles:
    - monitoring

- name: Setup admin-agents git
  hosts: vms
  roles:
    - admin-agents

- name: Setup wireguard machine
  hosts: wireguard
  roles:
    - wireguard

- name: Setup tvheadend machine
  hosts: tvheadend
  roles:
    - tvheadend

- name: Setup homeautomation git
  hosts: homeautomation
  roles:
    - home-automation

- name: Prune docker artefacts
  hosts: docker
  tasks:
    - name: Prune everything from docker
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true
        builder_cache: true
