- name: Install qemu-guest-agent
  hosts: vms
  roles:
    - qemu-agent

- name: Include a play for updating all machines
  ansible.builtin.import_playbook: update-machines.yml

- name: Setup adguardhome git
  hosts: adguardhome, adguardhome-nw
  roles:
    - adguardhome

- name: Setup homepage git
  hosts: homepage
  roles:
    - homepage

- name: Setup komodo git
  hosts: docker
  roles:
    - komodo

- name: Setup forgejo git
  hosts: monitoring
  roles:
    - forgejo

- name: Setup paperless machine
  hosts: paperless
  roles:
    - paperless-ngx
    - stirling-pdf

- name: Setup tvheadend machine
  hosts: tvheadend
  roles:
    - tvheadend
    - arr-services
    - container-updater

- name: Docker
  hosts: reverse-proxy
  roles:
    - git
    - docker

# - name: Setup homeautomation git
#   hosts: homeautomation
#   roles:
#     - home-automation

- name: Prune docker artefacts
  hosts: docker
  tasks:
    - name: Prune everything from docker
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true
        builder_cache: true
