- name: Upgrade alpine release
  hosts: alpine
  tasks:
    - name: Replace release channel version in alpine apk file
      become: true
      become_user: root
      become_method: community.general.doas
      ansible.builtin.replace:
        path: /etc/apk/repositories
        regexp: '^(?P<prefix>.+)v3\.20(?P<suffix>.+)$'
        replace: '\g<prefix>v3.22\g<suffix>'

    - name: Update repositories as a separate step
      become: true
      become_user: root
      become_method: community.general.doas
      community.general.apk:
        update_cache: true

    - name: Update repositories and update package apk-tools to latest version
      become: true
      become_user: root
      become_method: community.general.doas
      community.general.apk:
        name: apk-tools
        state: latest
        update_cache: true

    - name: Upgrade all packages on servers
      become: true
      become_user: root
      become_method: community.general.doas
      community.general.apk:
        update_cache: true
        upgrade: true
        available: true

    - name: Write cached content to disk
      ansible.builtin.command:
        cmd: sync

    - name: Reboot the machine
      become: true
      become_user: root
      become_method: community.general.doas
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible after upgrading alpine release"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
