- name: Download firezone automatic installation script
  ansible.builtin.get_url:
    url: https://github.com/firezone/firezone/raw/master/scripts/install.sh
    dest: /tmp/install.sh
    mode: '0770'


- name: Install firezone with the provided automatic installation script
  ansible.builtin.shell:
    cmd: printf 'max.lutz98@me.com\n\nhttps://firezone.lutz.fyi\nn\nn\ny\n\n' | /tmp/install.sh
    creates: /home/debian/.firezone
  register: myoutput

- ansible.builtin.debug:
    var: myoutput

# - name: Install firezone with the provided automatic installation script
#   ansible.builtin.expect:
#     command: bash /tmp/install.sh
#     echo: true
#     creates: /home/debian/installed
#     responses:
#       "administrator email": "max.lutz98@me.com"
#       "desired installation directory": ""
#       "external URL": "https://firezone.lutz.fyi"
#       "enable automatic SSL cert provisioning": "n"
#       "product feedback": "n"
#       "crash and performance logs": "y"
