---
- name: Reboot machine
  become: true
  become_user: root
  become_method: community.general.doas
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible to apply new kernel"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
