- name: Create new container with specified host options
  community.general.proxmox:
    api_user: "{{ api_user }}"
    api_password: "{{ proxmox_root_password }}"
    api_host: "{{ api_host }}"
    node: "{{ node }}"
    vmid: "{{ hostvars[item].vmid }}"
    ostemplate: "{{ hostvars[item].ostemplate }}"
    cores: "{{ hostvars[item].cores }}"
    memory: "{{ hostvars[item].memory }}"
    disk: "{{ hostvars[item].disk }}"
    netif: "{{ hostvars[item].netif }}"
    hostname: "{{ item }}"
    password: "{{ container_root_password }}"
    onboot: "{{ hostvars[item].onboot }}"
    unprivileged: "{{ hostvars[item].unprivileged }}"
    features: "{{ hostvars[item].features }}"
    description: "{{ hostvars[item].description }}"
    pubkey: "{{ hostvars[item].pubkey }}"
  loop: "{{ groups['containers'] }}"

- name: Start newly created container
  community.general.proxmox:
    api_user: "{{ api_user }}"
    api_password: "{{ proxmox_root_password }}"
    api_host: "{{ api_host }}"
    vmid: "{{ hostvars[item].vmid }}"
    unprivileged: "{{ hostvars[item].unprivileged }}"
    state: started
  loop: "{{ groups['containers'] }}"
