---

- name: Install git
  become: true
  become_user: root
  become_method: community.general.doas
  community.general.apk:
    name:
      - git
      - git-lfs
    state: latest
    update_cache: true
