---
- name: Handle docker dependencies and installation
  become: true
  become_user: root
  become_method: community.general.doas
  block:
    - name: Install docker
      community.general.apk:
        update_cache: true
        name:
          - docker
          - docker-cli-compose
          - python3
          - py3-requests
        state: latest

    - name: "Adding user to docker group: {{ ansible_user }}"
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
        state: present
      register: docker_group

    - name: Reboot the machine to apply group permissions
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible to apply new group permissions"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: docker_group.changed

    - name: Enable service docker
      ansible.builtin.service:
        name: docker
        enabled: true

    - name: Start service docker, if not started
      ansible.builtin.service:
        name: docker
        state: started
