---
- name: Handle docker dependencies and installation
  become: true
  become_user: root
  become_method: community.general.doas
  block:
    - name: Install docker
      community.general.apk:
        update_cache: true
        name:
          - docker
          - docker-cli-compose
          - python3
          - py3-requests
        state: latest

    - name: "Adding user to docker group: {{ ansible_user }}"
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
        state: present
      notify: Reboot machine

    - name: Enable service docker
      ansible.builtin.service:
        name: docker
        enabled: true

    - name: Start service docker, if not started
      ansible.builtin.service:
        name: docker
        state: started
