---

- name: Install all default software
  become: yes
  become_user: root
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: latest

- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/debian buster stable
    state: present

- name: Update apt and install docker-ce
  become: yes
  apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Enable docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Ensure group "somegroup" exists
  become: yes
  group:
    name: docker
    state: present

- name: Add user to group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Install docker-compose
  become: yes
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.26.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x,o+x'