---

- name: Install all docker dependencies
  become: true
  become_user: root
  ansible.builtin.apt:
    name:
      - ca-certificates
      - gnupg
      - python3-pip
    state: latest

- name: Add Docker GPG apt Key
  become: true
  become_user: root
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Add Docker Repository
  become: true
  become_user: root
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Install docker
  become: true
  become_user: root
  ansible.builtin.apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest

- name: Install Docker Module for Python
  become: true
  become_user: root
  ansible.builtin.pip:
    name: 
      - docker
      - docker-compose
    state: latest

- name: Adding {{ ansible_user }} to docker group
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
    state: present
